export const ANSWER_STORE_NAME = "ANSWER";
export const ANSWER_ACTION_TYPE = {
  SET_ANSWER_VALUE: "ANSWER_ACTION_TYPE.SET_ANSWER_VALUE",

  POST_ANSWER_PENDING: "ANSWER_ACTION_TYPE.POST_ANSWER_PENDING",
  POST_ANSWER_SUCCESS: "ANSWER_ACTION_TYPE.POST_ANSWER_SUCCESS",
  POST_ANSWER_FAILURE: "ANSWER_ACTION_TYPE.POST_ANSWER_FAILURE",

  GET_LAST_ANSWER_PENDING: "ANSWER_ACTION_TYPE.GET_LAST_ANSWER_PENDING",
  GET_LAST_ANSWER_SUCCESS: "ANSWER_ACTION_TYPE.GET_LAST_ANSWER_SUCCESS",
  GET_LAST_ANSWER_FAILURE: "ANSWER_ACTION_TYPE.GET_LAST_ANSWER_FAILURE",

  CHANGE_PRIORIRY: "ANSWER_ACTION_TYPE.CHANGE_PRIORIRY",
  PHRASE_INPUT_TYPE: "ANSWER_ACTION_TYPE.PHRASE_INPUT_TYPE",

  POST_CHANGE_PRIORITY_PENDING:
    "ANSWER_ACTION_TYPE.POST_CHANGE_PRIORITY_PENDING",
  POST_CHANGE_PRIORITY_SUCCESS:
    "ANSWER_ACTION_TYPE.POST_CHANGE_PRIORITY_SUCCESS",
  POST_CHANGE_PRIORITY_FAILURE:
    "ANSWER_ACTION_TYPE.POST_CHANGE_PRIORITY_FAILURE",
};
