export const CONSTRUCTOR_STORE_NAME = "CONSTRUCTOR";
export const CONSTRUCTOR_ACTION_TYPE = {
  GET_FOLDER_PENDING: "CONSTRUCTOR_ACTION_TYPE.GET_FOLDER_PENDING",
  GET_FOLDER_SUCCESS: "CONSTRUCTOR_ACTION_TYPE.GET_FOLDER_SUCCESS",
  GET_FOLDER_FAILURE: "CONSTRUCTOR_ACTION_TYPE.GET_FOLDER_FAILURE",

  GET_SUBFOLDER_PENDING: "CONSTRUCTOR_ACTION_TYPE.GET_SUBFOLDER_PENDING",
  GET_SUBFOLDER_SUCCESS: "CONSTRUCTOR_ACTION_TYPE.GET_SUBFOLDER_SUCCESS",
  GET_SUBFOLDER_FAILURE: "CONSTRUCTOR_ACTION_TYPE.GET_SUBFOLDER_FAILURE",

  GET_PHRASE_PENDING: "CONSTRUCTOR_ACTION_TYPE.GET_PHRASE_PENDING",
  GET_PHRASE_SUCCESS: "CONSTRUCTOR_ACTION_TYPE.GET_PHRASE_SUCCESS",
  GET_PHRASE_FAILURE: "CONSTRUCTOR_ACTION_TYPE.GET_PHRASE_FAILURE",
};
