export const HEADER_STORE_NAME = "HEADER";
export const HEADER_ACTION_TYPE = {
  LOGIN_REQUEST: "HEADER_ACTION_TYPE.LOGIN_REQUEST",
  LOGIN_PENDING: "HEADER_ACTION_TYPE.LOGIN_PENDING",
  LOGIN_SUCCESS: "HEADER_ACTION_TYPE.LOGIN_SUCCESS",

  LOGOUT: "HEADER_ACTION_TYPE.LOGOUT",
};
