export const detailArrayBasic = [
  { name: "Товаров", offered: true },
  { name: "Категорий", offered: true },
  { name: "Брендов", offered: true },
  { name: "Продавцов", offered: false },
  { name: "Размеров", offered: false },
  { name: "Цветов", offered: false },
  { name: "Складов", offered: false },
  { name: "Новинки", offered: false },
  { name: "Тренды", offered: false },
  { name: "Ценовая сегментация", offered: false },
  { name: "Позиции в категориях", offered: false },
  { name: "Поисковые запросы", offered: false },
  { name: "Изменение цен", offered: true },
  { name: "Рейтинги и отзывы", offered: true },
  { name: "Расширение для браузера", offered: true },
  { name: "Аналитика рекламы", offered: false },
  { name: "Аналитика контента", offered: true },
  { name: "Экспорт в файлы", offered: false },
];

export const detailArrayExpert = [
  { name: "Товаров", offered: true },
  { name: "Категорий", offered: true },
  { name: "Брендов", offered: true },
  { name: "Продавцов", offered: true },
  { name: "Размеров", offered: true },
  { name: "Цветов", offered: true },
  { name: "Складов", offered: false },
  { name: "Новинки", offered: true },
  { name: "Тренды", offered: true },
  { name: "Ценовая сегментация", offered: true },
  { name: "Позиции в категориях", offered: true },
  { name: "Поисковые запросы", offered: true },
  { name: "Изменение цен", offered: true },
  { name: "Рейтинги и отзывы", offered: true },
  { name: "Расширение для браузера", offered: true },
  { name: "Аналитика рекламы", offered: false },
  { name: "Аналитика контента", offered: true },
  { name: "Экспорт в файлы", offered: true },
];

export const detailArrayEnterprise = [
  { name: "Товаров", offered: true },
  { name: "Категорий", offered: true },
  { name: "Брендов", offered: true },
  { name: "Продавцов", offered: true },
  { name: "Размеров", offered: true },
  { name: "Цветов", offered: true },
  { name: "Складов", offered: false },
  { name: "Новинки", offered: true },
  { name: "Тренды", offered: true },
  { name: "Ценовая сегментация", offered: true },
  { name: "Позиции в категориях", offered: true },
  { name: "Поисковые запросы", offered: true },
  { name: "Изменение цен", offered: true },
  { name: "Рейтинги и отзывы", offered: true },
  { name: "Расширение для браузера", offered: true },
  { name: "Аналитика рекламы", offered: false },
  { name: "Аналитика контента", offered: true },
  { name: "Экспорт в файлы", offered: true },
];
