export const HOMEWORK_STORE_NAME = "HOMEWORK";

export const HOMEWORK_ACTION_TYPE = {
  POST_HOMEWORK_PENDING: "HOMEWORK_ACTION_TYPE.POST_HOMEWORK_PENDING",
  POST_HOMEWORK_SUCCESS: "HOMEWORK_ACTION_TYPE.POST_HOMEWORK_SUCCESS",
  POST_HOMEWORK_FAILURE: "HOMEWORK_ACTION_TYPE.POST_HOMEWORK_FAILURE",

  INPUT_TEXT_HOMEWORK: "HOMEWORK_ACTION_TYPE.INPUT_TEXT_HOMEWORK",
};
